2020-12-05 14:17:26,772 ERROR: Exception on /api/publications [GET] [in /home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask_httpauth.py", line 163, in decorated
    return f(*args, **kwargs)
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/app/api/publications.py", line 24, in get_publications
    data= Publication.to_collection_dict(Publication.query, page, par_page, 'api.get_publications', "publications")
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/app/modeles.py", line 27, in to_collection_dict
    'items':[item.to_dict() for item in ressources.items],
AttributeError: 'BaseQuery' object has no attribute 'items'
2020-12-05 14:18:14,153 INFO: Démarrage de petits Gazouillis [in /home/etudiant/projets/projetFinalReact/petits_gazouillis/app/__init__.py:52]
2020-12-05 17:42:35,989 INFO: Démarrage de petits Gazouillis [in /home/etudiant/projets/projetFinalReact/petits_gazouillis/app/__init__.py:52]
2020-12-05 21:03:17,155 INFO: Démarrage de petits Gazouillis [in /home/etudiant/projets/projetFinalReact/petits_gazouillis/app/__init__.py:52]
2020-12-05 21:18:41,096 ERROR: Exception on /api/suivre/4 [POST] [in /home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask_httpauth.py", line 163, in decorated
    return f(*args, **kwargs)
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/app/api/utilisateurs.py", line 35, in suivre
    if user.id == curent_user.id:
AttributeError: 'BaseQuery' object has no attribute 'id'
2020-12-05 21:20:22,148 ERROR: Exception on /api/suivre/4 [POST] [in /home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask_httpauth.py", line 163, in decorated
    return f(*args, **kwargs)
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/app/api/utilisateurs.py", line 35, in suivre
    #if user.id == curent_user.id:
AttributeError: 'BaseQuery' object has no attribute 'id'
2020-12-05 21:20:37,240 INFO: Démarrage de petits Gazouillis [in /home/etudiant/projets/projetFinalReact/petits_gazouillis/app/__init__.py:52]
2020-12-05 21:22:50,379 INFO: Démarrage de petits Gazouillis [in /home/etudiant/projets/projetFinalReact/petits_gazouillis/app/__init__.py:52]
2020-12-05 21:25:16,032 INFO: Démarrage de petits Gazouillis [in /home/etudiant/projets/projetFinalReact/petits_gazouillis/app/__init__.py:52]
2020-12-05 21:25:36,365 ERROR: Exception on /api/suivre/1 [POST] [in /home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/venv/lib/python3.7/site-packages/flask_httpauth.py", line 163, in decorated
    return f(*args, **kwargs)
  File "/home/etudiant/projets/projetFinalReact/petits_gazouillis/app/api/utilisateurs.py", line 35, in suivre
    print(user.id)
AttributeError: 'BaseQuery' object has no attribute 'id'
2020-12-05 21:26:17,565 INFO: Démarrage de petits Gazouillis [in /home/etudiant/projets/projetFinalReact/petits_gazouillis/app/__init__.py:52]
2020-12-05 21:27:07,324 INFO: Démarrage de petits Gazouillis [in /home/etudiant/projets/projetFinalReact/petits_gazouillis/app/__init__.py:52]
